# Generated by Django 4.1.7 on 2023-03-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_id',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='volunteer_id',
            new_name='volunteer',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
