# Generated by Django 4.1.7 on 2023-03-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0004_remove_login_id_alter_donation_donation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='day',
        ),
    ]
