# Generated by Django 4.1.7 on 2023-03-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0005_remove_bloodbank_day'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodbank',
            table='bloodbankApp_bloodbank',
        ),
        migrations.AlterModelTable(
            name='donation',
            table='bloodbankApp_donation',
        ),
        migrations.AlterModelTable(
            name='donor',
            table='bloodbankApp_donor',
        ),
        migrations.AlterModelTable(
            name='login',
            table='bloodbankApp_login',
        ),
        migrations.AlterModelTable(
            name='operatinghours',
            table='bloodbankApp_operatinghours',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='bloodbankApp_patient',
        ),
        migrations.AlterModelTable(
            name='staffmember',
            table='bloodbankApp_staffmember',
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table='bloodbankApp_volunteer',
        ),
    ]
