# Generated by Django 4.1.7 on 2023-03-31 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0006_alter_bloodbank_table_alter_donation_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodbank',
            table='Bloodbank',
        ),
        migrations.AlterModelTable(
            name='donation',
            table='Donation',
        ),
        migrations.AlterModelTable(
            name='donor',
            table='Donor',
        ),
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
        migrations.AlterModelTable(
            name='operatinghours',
            table='Operating Hours',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
        migrations.AlterModelTable(
            name='staffmember',
            table='Staff Member',
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table='Volunteer',
        ),
    ]
