# Generated by Django 4.1.7 on 2023-03-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0009_alter_donation_blood_type_alter_donor_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='health_interview',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='training',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')]),
        ),
    ]
